# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-replicas
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mysql
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the primary: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: mysql-replicas
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sidecar-mysql-monitoring
  namespace: mysql-replicas
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      
  namespaceSelector:
    any: false
  endpoints:
  - port: mysql-metrics
    interval: 30s

---
apiVersion: v1
kind: Service
metadata:
  name: myphpadmin
  namespace: mysql-replicas
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: myphpadmin
