apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-persistent-storage
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/grafana"