apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Alexrubiolv/mysql-replica
    targetRevision: HEAD
    path: mySQL/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
